"""empty message

Revision ID: 7d62c83bf202
Revises: a63aa9b3a1fb
Create Date: 2025-09-28 16:07:22.494488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d62c83bf202'
down_revision: Union[str, None] = 'a63aa9b3a1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewers', sa.Column('wish', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('reviewers', 'wish_drink')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewers', sa.Column('wish_drink', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('reviewers', 'wish')
    # ### end Alembic commands ###
