"""first alembic

Revision ID: a63aa9b3a1fb
Revises: 
Create Date: 2025-09-28 15:27:56.461321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a63aa9b3a1fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('channel', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('birthday', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('wish_drink', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('service', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('msg', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('events', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('memo', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_reviewers_events'), 'reviewers', ['events'], unique=False)
    op.create_index(op.f('ix_reviewers_link'), 'reviewers', ['link'], unique=False)
    op.create_index(op.f('ix_reviewers_name'), 'reviewers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('usertype', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('org_name', sa.String(length=50), nullable=True),
    sa.Column('store_name', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_index(op.f('ix_users_permission'), 'users', ['permission'], unique=False)
    op.create_index(op.f('ix_users_usertype'), 'users', ['usertype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_usertype'), table_name='users')
    op.drop_index(op.f('ix_users_permission'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reviewers_name'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_link'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_events'), table_name='reviewers')
    op.drop_table('reviewers')
    # ### end Alembic commands ###
