"""empty message

Revision ID: 145646b32297
Revises: f6dca557af63
Create Date: 2024-04-08 16:56:25.792940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '145646b32297'
down_revision: Union[str, None] = 'f6dca557af63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sns_birthyear', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('sns_birthday', sa.String(length=10), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user', 'sns_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sns_birth', mysql.VARCHAR(length=10), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('user', 'sns_birthday')
    op.drop_column('user', 'sns_birthyear')
    # ### end Alembic commands ###
