"""empty message

Revision ID: 155e4a01f4bb
Revises: c2c5b82072c3
Create Date: 2024-03-05 14:45:14.495537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '155e4a01f4bb'
down_revision: Union[str, None] = 'c2c5b82072c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
