"""empty message

Revision ID: 1b38aebd1faa
Revises: 2f7e4ea8b67c
Create Date: 2024-09-24 13:37:38.661640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b38aebd1faa'
down_revision: Union[str, None] = '2f7e4ea8b67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('orgname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'orgname')
    # ### end Alembic commands ###
