"""empty message

Revision ID: 3667f5bdf3b3
Revises: 10ddfc3c502d
Create Date: 2024-04-07 12:48:32.967510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3667f5bdf3b3'
down_revision: Union[str, None] = '10ddfc3c502d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sns_gender', sa.String(length=2), nullable=True))
    op.add_column('user', sa.Column('sns_age', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('sns_birth', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sns_birth')
    op.drop_column('user', 'sns_age')
    op.drop_column('user', 'sns_gender')
    # ### end Alembic commands ###
