"""empty message

Revision ID: 36be7225275d
Revises: 155e4a01f4bb
Create Date: 2024-03-05 14:50:11.435943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36be7225275d'
down_revision: Union[str, None] = '155e4a01f4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
