"""empty message

Revision ID: 4452de7d81a2
Revises: 21723cbc72ab
Create Date: 2024-11-25 14:09:05.913039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4452de7d81a2'
down_revision: Union[str, None] = '21723cbc72ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('subject', mysql.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'subject')
    # ### end Alembic commands ###
