"""empty message

Revision ID: 55c9283dad28
Revises: d2a9482ad23c
Create Date: 2024-03-18 15:00:04.248456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c9283dad28'
down_revision: Union[str, None] = 'd2a9482ad23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id', new_column_name='userid', existing_type=sa.String(100), type_=sa.String(200))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
