"""empty message

Revision ID: 7c7567d2096d
Revises: 08a1af9d9ff8
Create Date: 2024-04-05 13:56:05.148433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7567d2096d'
down_revision: Union[str, None] = '08a1af9d9ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_index('sns_type', table_name='user')
    op.drop_index('username_2', table_name='user')
    op.create_index(op.f('ix_user_sns_type'), 'user', ['sns_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sns_type'), table_name='user')
    op.create_index('username_2', 'user', ['username'], unique=True)
    op.create_index('sns_type', 'user', ['sns_type'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
