"""empty message

Revision ID: 9aa5322fc389
Revises: 145646b32297
Create Date: 2024-04-08 17:05:14.379894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aa5322fc389'
down_revision: Union[str, None] = '145646b32297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'sns_gender',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'sns_gender',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###
