"""empty message

Revision ID: a7147fc388c5
Revises: e067110934da
Create Date: 2024-03-18 14:34:56.514813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7147fc388c5'
down_revision: Union[str, None] = 'e067110934da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_index('userid', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('userid', 'user', ['userid'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
