"""empty message

Revision ID: b654382dfe5b
Revises: 6632ce3815f2
Create Date: 2024-03-18 15:21:15.952340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b654382dfe5b'
down_revision: Union[str, None] = '6632ce3815f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('userid', sa.String(length=100), nullable=False))
    # op.drop_index('username', table_name='user')
    # op.create_unique_constraint(None, 'user', ['userid'])
    # op.drop_column('user', 'user_id')
    op.alter_column('user', 'user_id',
               new_column_name='userid',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=170),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', mysql.VARCHAR(length=170), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['user_id'], unique=True)
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###
