"""empty message

Revision ID: b862cfb16417
Revises: 55c9283dad28
Create Date: 2024-03-18 15:10:50.956434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b862cfb16417'
down_revision: Union[str, None] = '55c9283dad28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_index('username', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('user', sa.Column('user_id', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['user_id'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
