"""empty message

Revision ID: b86f27588f72
Revises: 96ede1374a2f
Create Date: 2024-10-01 16:38:17.632427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b86f27588f72'
down_revision: Union[str, None] = '96ede1374a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('title', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('portfolio', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('portfolio', 'title')
    # ### end Alembic commands ###
