"""empty message

Revision ID: ba36be4cb95e
Revises: c7094f37d2c5
Create Date: 2024-04-16 12:56:58.374074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba36be4cb95e'
down_revision: Union[str, None] = 'c7094f37d2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('value', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('status', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('doc_01', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('doc_02', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
