"""empty message

Revision ID: d2a9482ad23c
Revises: a7147fc388c5
Create Date: 2024-03-18 14:47:07.890407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd2a9482ad23c'
down_revision: Union[str, None] = 'a7147fc388c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'userid')
    op.alter_column('user', 'username', new_column_name='user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
