"""empty message

Revision ID: d3f22ffce73e
Revises: 70ff9c8c4696
Create Date: 2024-10-12 12:17:03.315451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3f22ffce73e'
down_revision: Union[str, None] = '70ff9c8c4696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('content', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'content')
    # ### end Alembic commands ###
