"""empty message

Revision ID: d948994b35cd
Revises: 4b93166c2db5
Create Date: 2024-04-05 12:32:19.097162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd948994b35cd'
down_revision: Union[str, None] = '4b93166c2db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('answer', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('question', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('nickname', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('modify_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('sns_type', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('sns_id', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('sns_connect_date', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['sns_type'])
    op.create_unique_constraint(None, 'user', ['sns_id'])
    op.create_unique_constraint(None, 'user', ['sns_connect_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'sns_connect_date')
    op.drop_column('user', 'sns_id')
    op.drop_column('user', 'sns_type')
    op.drop_column('user', 'create_date')
    op.drop_column('user', 'modify_date')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'username')
    op.alter_column('question', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('answer', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('answer', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
