"""empty message

Revision ID: e067110934da
Revises: 10d75f0eebe1
Create Date: 2024-03-18 14:27:21.924951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e067110934da'
down_revision: Union[str, None] = '10d75f0eebe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', sa.String(length=100), nullable=False))
    op.drop_index('username', table_name='user')
    op.create_unique_constraint(None, 'user', ['userid'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###
