"""empty message

Revision ID: e731f0ac3eb1
Revises: d76be98737e5
Create Date: 2024-04-23 18:12:34.638771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e731f0ac3eb1'
down_revision: Union[str, None] = 'd76be98737e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('modify_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'modify_date')
    # ### end Alembic commands ###
