"""empty message

Revision ID: f2b3e5521c87
Revises: b862cfb16417
Create Date: 2024-03-18 15:11:45.926041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2b3e5521c87'
down_revision: Union[str, None] = 'b862cfb16417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', mysql.VARCHAR(length=100), nullable=False))
    op.alter_column('user', 'user_id',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
