"""empty message

Revision ID: f6dca557af63
Revises: e0371cb420d5
Create Date: 2024-04-07 15:13:09.841337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dca557af63'
down_revision: Union[str, None] = 'e0371cb420d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usertype', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_user_usertype'), 'user', ['usertype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usertype'), table_name='user')
    op.drop_column('user', 'usertype')
    # ### end Alembic commands ###
