"""empty message

Revision ID: ff3690affb4e
Revises: e731f0ac3eb1
Create Date: 2024-04-23 18:21:30.359469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff3690affb4e'
down_revision: Union[str, None] = 'e731f0ac3eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'modify_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'modify_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
