"""empty message

Revision ID: 1fdb95bffc94
Revises: 82a32857ea3c
Create Date: 2025-08-28 17:20:43.552022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1fdb95bffc94'
down_revision: Union[str, None] = '82a32857ea3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rozone_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('contents', mysql.LONGTEXT(), nullable=True),
    sa.Column('public', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('images', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rozone_news')
    # ### end Alembic commands ###
