"""empty message

Revision ID: 31cc86b27385
Revises: e3a36dd3d386
Create Date: 2025-06-07 17:09:32.310003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31cc86b27385'
down_revision: Union[str, None] = 'e3a36dd3d386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapoclean_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('contents', mysql.LONGTEXT(), nullable=True),
    sa.Column('images', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapoclean_works')
    # ### end Alembic commands ###
