"""empty message

Revision ID: 3b3af89a32f1
Revises: 31cc86b27385
Create Date: 2025-06-12 15:19:49.980737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b3af89a32f1'
down_revision: Union[str, None] = '31cc86b27385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('_users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('_users', 'phone',
               existing_type=mysql.VARCHAR(length=13),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('_users', 'phone',
               existing_type=mysql.VARCHAR(length=13),
               nullable=False)
    op.alter_column('_users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
