"""empty message

Revision ID: 5ff2955213ea
Revises: 3b3af89a32f1
Create Date: 2025-06-14 15:03:47.319672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ff2955213ea'
down_revision: Union[str, None] = '3b3af89a32f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapoclean_works', sa.Column('public', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapoclean_works', 'public')
    # ### end Alembic commands ###
