"""empty message

Revision ID: 82a32857ea3c
Revises: 28733b5b6cf2
Create Date: 2025-07-15 13:52:39.080140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82a32857ea3c'
down_revision: Union[str, None] = '28733b5b6cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eightpointone_partners', sa.Column('link', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('eightpointone_partners', sa.Column('category', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eightpointone_partners', 'category')
    op.drop_column('eightpointone_partners', 'link')
    # ### end Alembic commands ###
