"""empty message

Revision ID: e3a36dd3d386
Revises: 
Create Date: 2025-06-02 18:42:24.742104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3a36dd3d386'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('usertype', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('orgname', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_index(op.f('ix__users_permission'), '_users', ['permission'], unique=False)
    op.create_index(op.f('ix__users_usertype'), '_users', ['usertype'], unique=False)
    op.create_table('_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('value', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('status', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_category')
    op.drop_index(op.f('ix__users_usertype'), table_name='_users')
    op.drop_index(op.f('ix__users_permission'), table_name='_users')
    op.drop_table('_users')
    # ### end Alembic commands ###
