"""empty message

Revision ID: f5adbedc3e67
Revises: 5ff2955213ea
Create Date: 2025-06-14 15:04:55.975355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5adbedc3e67'
down_revision: Union[str, None] = '5ff2955213ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapoclean_works', sa.Column('modify_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapoclean_works', 'modify_date')
    # ### end Alembic commands ###
