"""empty message

Revision ID: 05b125b468ab
Revises: 5a519666e364
Create Date: 2025-02-01 13:24:48.936180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05b125b468ab'
down_revision: Union[str, None] = '5a519666e364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webpush', sa.Column('endpoint', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webpush', 'endpoint')
    # ### end Alembic commands ###
