"""empty message

Revision ID: 0b7c4da7929a
Revises: 359b4caf35d8
Create Date: 2025-02-09 14:45:35.599465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b7c4da7929a'
down_revision: Union[str, None] = '359b4caf35d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('msg', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'msg')
    # ### end Alembic commands ###
