"""empty message

Revision ID: 1f6e6c1e51c8
Revises: b77949f8d8e4
Create Date: 2025-02-01 15:10:18.029181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f6e6c1e51c8'
down_revision: Union[str, None] = 'b77949f8d8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webpush', 'msg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webpush', sa.Column('msg', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###
