"""empty message

Revision ID: 2013fba46330
Revises: 216b04d268ec
Create Date: 2025-02-13 13:40:57.915601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2013fba46330'
down_revision: Union[str, None] = '216b04d268ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webpush_log')
    # ### end Alembic commands ###
