"""empty message

Revision ID: 216b04d268ec
Revises: 3b6947267ab0
Create Date: 2025-02-11 15:09:54.825132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '216b04d268ec'
down_revision: Union[str, None] = '3b6947267ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_group', sa.Column('sale_date', mysql.VARCHAR(length=10), nullable=False))
    op.create_index(op.f('ix_order_group_sale_date'), 'order_group', ['sale_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_group_sale_date'), table_name='order_group')
    op.drop_column('order_group', 'sale_date')
    # ### end Alembic commands ###
