"""empty message

Revision ID: 2a60a11143d7
Revises: 9087aa2e6f7b
Create Date: 2025-02-09 14:38:28.139370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a60a11143d7'
down_revision: Union[str, None] = '9087aa2e6f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_group', sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('order_group', sa.Column('table_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('order_group', sa.Column('status', mysql.VARCHAR(length=10), nullable=False))
    op.create_index(op.f('ix_order_group_status'), 'order_group', ['status'], unique=False)
    op.create_index(op.f('ix_order_group_store_id'), 'order_group', ['store_id'], unique=False)
    op.create_index(op.f('ix_order_group_table_id'), 'order_group', ['table_id'], unique=False)
    op.drop_index('ix_orders_order_id', table_name='orders')
    op.drop_index('ix_orders_store_id', table_name='orders')
    op.drop_index('ix_orders_table_id', table_name='orders')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'table_id')
    op.drop_column('orders', 'store_id')
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('orders', sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('orders', sa.Column('table_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('orders', sa.Column('status', mysql.VARCHAR(length=10), nullable=False))
    op.create_index('ix_orders_table_id', 'orders', ['table_id'], unique=False)
    op.create_index('ix_orders_store_id', 'orders', ['store_id'], unique=False)
    op.create_index('ix_orders_order_id', 'orders', ['order_id'], unique=False)
    op.drop_index(op.f('ix_order_group_table_id'), table_name='order_group')
    op.drop_index(op.f('ix_order_group_store_id'), table_name='order_group')
    op.drop_index(op.f('ix_order_group_status'), table_name='order_group')
    op.drop_column('order_group', 'status')
    op.drop_column('order_group', 'table_id')
    op.drop_column('order_group', 'store_id')
    # ### end Alembic commands ###
