"""empty message

Revision ID: 359b4caf35d8
Revises: 2a60a11143d7
Create Date: 2025-02-09 14:41:26.022376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '359b4caf35d8'
down_revision: Union[str, None] = '2a60a11143d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_group_order_id', table_name='order_group')
    op.drop_index('key', table_name='order_group')
    op.create_unique_constraint(None, 'order_group', ['order_id'])
    op.drop_column('order_group', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_group', sa.Column('key', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'order_group', type_='unique')
    op.create_index('key', 'order_group', ['key'], unique=True)
    op.create_index('ix_order_group_order_id', 'order_group', ['order_id'], unique=False)
    # ### end Alembic commands ###
