"""empty message

Revision ID: 3b6947267ab0
Revises: 0b7c4da7929a
Create Date: 2025-02-09 14:51:24.960847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b6947267ab0'
down_revision: Union[str, None] = '0b7c4da7929a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', mysql.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###
