"""empty message

Revision ID: 5a45830c2e2a
Revises: d6d691b8fcd1
Create Date: 2025-07-21 18:27:51.424776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a45830c2e2a'
down_revision: Union[str, None] = 'd6d691b8fcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('usertype', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('orgname', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_index(op.f('ix_users_permission'), 'users', ['permission'], unique=False)
    op.create_index(op.f('ix_users_usertype'), 'users', ['usertype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_usertype'), table_name='users')
    op.drop_index(op.f('ix_users_permission'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
