"""empty message

Revision ID: 5a519666e364
Revises: 5f571289ff4d
Create Date: 2025-01-26 13:50:00.932567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a519666e364'
down_revision: Union[str, None] = '5f571289ff4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('subscription', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('msg', mysql.LONGTEXT(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webpush')
    # ### end Alembic commands ###
