"""empty message

Revision ID: 62a7b03a66b6
Revises: ea8735e8e0fe
Create Date: 2025-07-28 14:06:58.644365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62a7b03a66b6'
down_revision: Union[str, None] = 'ea8735e8e0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewers', sa.Column('memo', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('reviewers', 'channel',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('reviewers', 'link',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('reviewers', 'wish_drink',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('reviewers', 'msg',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviewers', 'msg',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('reviewers', 'wish_drink',
               existing_type=mysql.VARCHAR(length=128),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('reviewers', 'link',
               existing_type=mysql.VARCHAR(length=1000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('reviewers', 'channel',
               existing_type=mysql.VARCHAR(length=128),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.drop_column('reviewers', 'memo')
    # ### end Alembic commands ###
