"""empty message

Revision ID: 9956fc4a6753
Revises: fb29236aa47c
Create Date: 2024-11-25 14:31:50.134569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9956fc4a6753'
down_revision: Union[str, None] = 'fb29236aa47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine')
    # ### end Alembic commands ###
