"""empty message

Revision ID: a3059030afe7
Revises: cbc1973d3418
Create Date: 2025-02-09 14:27:10.859940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3059030afe7'
down_revision: Union[str, None] = 'cbc1973d3418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_group', sa.Column('order_id', mysql.VARCHAR(length=50), nullable=False))
    op.drop_index('ix_order_group_status', table_name='order_group')
    op.drop_index('ix_order_group_store_id', table_name='order_group')
    op.drop_index('ix_order_group_table_id', table_name='order_group')
    op.create_index(op.f('ix_order_group_order_id'), 'order_group', ['order_id'], unique=False)
    op.drop_column('order_group', 'status')
    op.drop_column('order_group', 'store_id')
    op.drop_column('order_group', 'table_id')
    op.add_column('orders', sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('orders', sa.Column('table_id', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('orders', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.alter_column('orders', 'order_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('orders', 'table_id')
    op.drop_column('orders', 'store_id')
    op.add_column('order_group', sa.Column('table_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('order_group', sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('order_group', sa.Column('status', mysql.VARCHAR(length=10), nullable=False))
    op.drop_index(op.f('ix_order_group_order_id'), table_name='order_group')
    op.create_index('ix_order_group_table_id', 'order_group', ['table_id'], unique=False)
    op.create_index('ix_order_group_store_id', 'order_group', ['store_id'], unique=False)
    op.create_index('ix_order_group_status', 'order_group', ['status'], unique=False)
    op.drop_column('order_group', 'order_id')
    # ### end Alembic commands ###
