"""empty message

Revision ID: ab605abc12af
Revises: 62a7b03a66b6
Create Date: 2025-08-24 15:26:48.939525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab605abc12af'
down_revision: Union[str, None] = '62a7b03a66b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewers', sa.Column('service', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviewers', 'service')
    # ### end Alembic commands ###
