"""empty message

Revision ID: c14122d04ac0
Revises: 5ff808fbec9c
Create Date: 2024-08-19 18:23:20.743312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c14122d04ac0'
down_revision: Union[str, None] = '5ff808fbec9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'sns_birthday',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'sns_birthday',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###
