"""empty message

Revision ID: cbc1973d3418
Revises: 18dbb781b00f
Create Date: 2025-02-09 14:05:32.695199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbc1973d3418'
down_revision: Union[str, None] = '18dbb781b00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_order_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_store_id', table_name='orders')
    op.drop_index('ix_orders_table_id', table_name='orders')
    op.drop_column('orders', 'table_id')
    op.drop_column('orders', 'store_id')
    op.drop_column('orders', 'order_id')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('orders', sa.Column('order_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('orders', sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('orders', sa.Column('table_id', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('ix_orders_table_id', 'orders', ['table_id'], unique=False)
    op.create_index('ix_orders_store_id', 'orders', ['store_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_order_id', 'orders', ['order_id'], unique=False)
    # ### end Alembic commands ###
