"""empty message

Revision ID: d013a7a1b652
Revises: 
Create Date: 2024-07-09 13:27:02.105529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd013a7a1b652'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('usertype', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('sns_type', sa.String(length=50), nullable=False),
    sa.Column('sns_id', sa.String(length=50), nullable=False),
    sa.Column('sns_name', sa.String(length=50), nullable=True),
    sa.Column('sns_gender', sa.String(length=10), nullable=True),
    sa.Column('sns_age', sa.String(length=10), nullable=True),
    sa.Column('sns_birthyear', sa.String(length=10), nullable=True),
    sa.Column('sns_birthday', sa.String(length=10), nullable=True),
    sa.Column('sns_connect_date', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sns_id'),
    sa.UniqueConstraint('userid')
    )
    op.create_index(op.f('ix_user_permission'), 'user', ['permission'], unique=False)
    op.create_index(op.f('ix_user_sns_type'), 'user', ['sns_type'], unique=False)
    op.create_index(op.f('ix_user_usertype'), 'user', ['usertype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usertype'), table_name='user')
    op.drop_index(op.f('ix_user_sns_type'), table_name='user')
    op.drop_index(op.f('ix_user_permission'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
