"""empty message

Revision ID: d6d691b8fcd1
Revises: 48bf73a20821
Create Date: 2025-02-22 14:41:18.030953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6d691b8fcd1'
down_revision: Union[str, None] = '48bf73a20821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webpush', sa.Column('status', mysql.VARCHAR(length=10), nullable=True))
    op.create_index(op.f('ix_webpush_status'), 'webpush', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webpush_status'), table_name='webpush')
    op.drop_column('webpush', 'status')
    # ### end Alembic commands ###
