"""Initial migration

Revision ID: e24d41dae8c0
Revises: 
Create Date: 2025-02-18 14:50:49.048033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e24d41dae8c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('channel', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('birthday', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('link', mysql.LONGTEXT(), nullable=False),
    sa.Column('wish_drink', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('msg', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_reviewers_channel'), 'reviewers', ['channel'], unique=False)
    op.create_index(op.f('ix_reviewers_gender'), 'reviewers', ['gender'], unique=False)
    op.create_index(op.f('ix_reviewers_link'), 'reviewers', ['link'], unique=False)
    op.create_index(op.f('ix_reviewers_wish_drink'), 'reviewers', ['wish_drink'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewers_wish_drink'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_link'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_gender'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_channel'), table_name='reviewers')
    op.drop_table('reviewers')
    # ### end Alembic commands ###
