"""empty message

Revision ID: ea8735e8e0fe
Revises: 5a45830c2e2a
Create Date: 2025-07-25 14:40:59.126154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea8735e8e0fe'
down_revision: Union[str, None] = '5a45830c2e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewers', sa.Column('events', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('reviewers', sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
    op.drop_index('ix_reviewers_channel', table_name='reviewers', mysql_length={'channel': 768})
    op.drop_index('ix_reviewers_gender', table_name='reviewers')
    op.drop_index('ix_reviewers_wish_drink', table_name='reviewers', mysql_length={'wish_drink': 768})
    op.create_index(op.f('ix_reviewers_events'), 'reviewers', ['events'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewers_events'), table_name='reviewers')
    op.create_index('ix_reviewers_wish_drink', 'reviewers', ['wish_drink'], unique=False, mysql_length={'wish_drink': 768})
    op.create_index('ix_reviewers_gender', 'reviewers', ['gender'], unique=False)
    op.create_index('ix_reviewers_channel', 'reviewers', ['channel'], unique=False, mysql_length={'channel': 768})
    op.drop_column('reviewers', 'status')
    op.drop_column('reviewers', 'events')
    # ### end Alembic commands ###
