name: Build and Deploy

on:
  push:
    branches: 
      [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Copy file via scp
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_IP }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.REMOTE_SSH_PORT }}
      #     source: "dist/,package.json"
      #     target: "~/projects/nestjs"
      #     rm: true

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --exclude='.git' --exclude='.github' --exclude='.gitignore'
          path: ./
          remote_path: ~/projects/fastapi
          remote_host: ${{ secrets.REMOTE_IP }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.REMOTE_SSH_PORT }}

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd ~/projects/fastapi
            source ~/venvs/fastapi/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi